x-airflow-common: &airflow-common
  build: .
  environment:
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

    - AIRFLOW__WEBSERVER__SECRET_KEY=sua_chave_secreta_qualquer_123456789

    - KAGGLE_USERNAME=${KAGGLE_USERNAME}
    - KAGGLE_KEY=${KAGGLE_KEY}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - S3_BUCKET_NAME=${S3_BUCKET_NAME}

    - AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT=300
    - AIRFLOW__WEBSERVER__WORKERS=2
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - CONNECTION_CHECK_MAX_COUNT=0